<!DOCTYPE html>
<html lang = "en">
<head>
	<title> Cryptoguru Home </title>
	<meta charset="utf-8">
	<link rel = "stylesheet" type = "text/css" href = "./CryptoHome.css">
	<script src = "./CryptoHome.js"></script>
</head>
<body>
	<div class = "Header">
		<h2>Cryptogurus</h2>

		<div class = "navBar">
			<table width = 100%>
				<tr>
					<td>
						<div class = "Home"><a href = "./filler.html"><h4>Home</h4></a></div>
					</td>
					<td>
						<div class = "News"><a href = "./filler.html"><h4>News</h4></a></div>
					</td>
					<td>
						<div class = "Crypto Explained"><a href = "./filler.html"><h4>Crypto Explained</h4></a></div>
					</td>
					<td>
						<div class = "Starter Guide"><a href = "./filler.html"><h4>Starter Guide</h4></a></div>
					</td>
				</tr>
			</table>
		</div>
		
		<img src = "./logo.png" width = 20% height = 20% class = "leftLogo">
		<img src = "./logo.png" width = 20% height = 20% class = "rightLogo">
	</div>